package de.randomreforges.blockentity;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

import net.minecraft.client.model.Model;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.RenderType;

/*****************************************************************************************************************************************************************
99.9% of this script has been generated by Blockbench and I know that I need to optimize it. Ill do this in a later update (never touch a running system or whatever)
*****************************************************************************************************************************************************************/


public class ReforgeCageModel extends Model {
	public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(new ResourceLocation("randomreforges", "reforge_cage"), "main");
	private final ModelPart PillarMiddle;
	private final ModelPart Pillars;
	private final ModelPart CircleSouth;
	private final ModelPart CircleNorth;
	private final ModelPart CircleWest;
	private final ModelPart CircleEast;
	private final ModelPart Animation;
	private final ModelPart bb_main;

	public ReforgeCageModel(ModelPart root) {
		super(RenderType::entityCutout);
		this.PillarMiddle = root.getChild("PillarMiddle");
		this.Pillars = root.getChild("Pillars");
		this.CircleSouth = root.getChild("CircleSouth");
		this.CircleNorth = root.getChild("CircleNorth");
		this.CircleWest = root.getChild("CircleWest");
		this.CircleEast = root.getChild("CircleEast");
		this.Animation = root.getChild("Animation");
		this.bb_main = root.getChild("bb_main");
	}

	public static LayerDefinition createBodyLayer() {
		MeshDefinition meshdefinition = new MeshDefinition();
		PartDefinition partdefinition = meshdefinition.getRoot();

		PartDefinition PillarMiddle = partdefinition.addOrReplaceChild("PillarMiddle", CubeListBuilder.create().texOffs(38, 34).addBox(-1.0F, 3.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F))
		.texOffs(30, 34).addBox(-1.0F, -7.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 16.0F, 0.0F));

		PartDefinition Pillars = partdefinition.addOrReplaceChild("Pillars", CubeListBuilder.create().texOffs(6, 34).addBox(7.0F, -7.0F, 6.0F, 1.0F, 14.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(6, 34).addBox(7.0F, -7.0F, -7.0F, 1.0F, 14.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(0, 34).addBox(6.0F, -7.0F, -8.0F, 2.0F, 14.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(6, 34).addBox(-8.0F, -7.0F, -7.0F, 1.0F, 14.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(6, 34).addBox(-8.0F, -7.0F, 6.0F, 1.0F, 14.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 16.0F, 0.0F));

		PartDefinition cube_r1 = Pillars.addOrReplaceChild("cube_r1", CubeListBuilder.create().texOffs(0, 34).addBox(-1.0F, -7.0F, -0.5F, 2.0F, 14.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, 0.0F, -7.5F, 0.0F, 0.0F, -3.1416F));

		PartDefinition cube_r2 = Pillars.addOrReplaceChild("cube_r2", CubeListBuilder.create().texOffs(0, 34).addBox(-1.0F, -7.0F, -0.5F, 2.0F, 14.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, 0.0F, 7.5F, 0.0F, 3.1416F, 0.0F));

		PartDefinition cube_r3 = Pillars.addOrReplaceChild("cube_r3", CubeListBuilder.create().texOffs(0, 34).addBox(-1.0F, -7.0F, -0.5F, 2.0F, 14.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, 0.0F, 7.5F, -3.1416F, 0.0F, 0.0F));

		PartDefinition CircleSouth = partdefinition.addOrReplaceChild("CircleSouth", CubeListBuilder.create().texOffs(42, 40).addBox(2.0F, 4.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 42).addBox(4.0F, 2.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 42).addBox(4.0F, -4.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(28, 40).addBox(-6.0F, -2.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 42).addBox(-5.0F, 2.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 42).addBox(-5.0F, -4.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(10, 39).addBox(-2.0F, 5.0F, -0.5F, 4.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(28, 40).addBox(5.0F, -2.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 40).addBox(-4.0F, 4.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 40).addBox(2.0F, -5.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(10, 39).addBox(-2.0F, -6.0F, -0.5F, 4.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 40).addBox(-4.0F, -5.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 16.0F, 7.5F));

		PartDefinition CircleNorth = partdefinition.addOrReplaceChild("CircleNorth", CubeListBuilder.create().texOffs(42, 40).addBox(2.0F, 4.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 42).addBox(4.0F, 2.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 42).addBox(4.0F, -4.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(28, 40).addBox(-6.0F, -2.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 42).addBox(-5.0F, 2.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 42).addBox(-5.0F, -4.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(10, 39).addBox(-2.0F, 5.0F, -0.5F, 4.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(28, 40).addBox(5.0F, -2.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 40).addBox(-4.0F, 4.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 40).addBox(2.0F, -5.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(10, 39).addBox(-2.0F, -6.0F, -0.5F, 4.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(42, 40).addBox(-4.0F, -5.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 16.0F, -7.5F));

		PartDefinition CircleWest = partdefinition.addOrReplaceChild("CircleWest", CubeListBuilder.create().texOffs(20, 43).addBox(-0.5F, 2.0F, 4.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(20, 43).addBox(-0.5F, -4.0F, 4.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(32, 40).addBox(-0.5F, -2.0F, -6.0F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(20, 43).addBox(-0.5F, 2.0F, -5.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(20, 43).addBox(-0.5F, -4.0F, -5.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(10, 34).addBox(-0.5F, 5.0F, -2.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F))
		.texOffs(10, 34).addBox(-0.5F, -6.0F, -2.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F))
		.texOffs(32, 40).addBox(-0.5F, -2.0F, 5.0F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(36, 40).addBox(-0.5F, 4.0F, 2.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
		.texOffs(36, 40).addBox(-0.5F, -5.0F, 2.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
		.texOffs(36, 40).addBox(-0.5F, -5.0F, -4.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
		.texOffs(36, 40).addBox(-0.5F, 4.0F, -4.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offset(7.5F, 16.0F, 0.0F));

		PartDefinition CircleEast = partdefinition.addOrReplaceChild("CircleEast", CubeListBuilder.create().texOffs(24, 43).addBox(-0.5F, 2.0F, 4.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(24, 43).addBox(-0.5F, -4.0F, 4.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(10, 41).addBox(-0.5F, -2.0F, -6.0F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(24, 43).addBox(-0.5F, 2.0F, -5.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(24, 43).addBox(-0.5F, -4.0F, -5.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(20, 34).addBox(-0.5F, 5.0F, -2.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F))
		.texOffs(20, 34).addBox(-0.5F, -6.0F, -2.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F))
		.texOffs(10, 41).addBox(-0.5F, -2.0F, 5.0F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F))
		.texOffs(14, 41).addBox(-0.5F, 4.0F, 2.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
		.texOffs(14, 41).addBox(-0.5F, -5.0F, 2.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
		.texOffs(14, 41).addBox(-0.5F, -5.0F, -4.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
		.texOffs(14, 41).addBox(-0.5F, 4.0F, -4.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offset(-7.5F, 16.0F, 0.0F));

		PartDefinition Animation = partdefinition.addOrReplaceChild("Animation", CubeListBuilder.create().texOffs(20, 39).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 16.0F, 0.0F));

		PartDefinition bb_main = partdefinition.addOrReplaceChild("bb_main", CubeListBuilder.create().texOffs(0, 0).addBox(-8.0F, -16.0F, -8.0F, 16.0F, 1.0F, 16.0F, new CubeDeformation(0.0F))
		.texOffs(0, 17).addBox(-8.0F, -1.0F, -8.0F, 16.0F, 1.0F, 16.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

		return LayerDefinition.create(meshdefinition, 64, 64);
	}

	public void setupAnim(float ageInTicks) {
		this.Animation.yRot = ageInTicks * 0.1F;
		this.Animation.y = 16.0F + (float)Math.sin(ageInTicks * 0.1F) * 1.0F;
	}



	@Override
	public void renderToBuffer(PoseStack poseStack, VertexConsumer vertexConsumer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
		PillarMiddle.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
		Pillars.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
		CircleSouth.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
		CircleNorth.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
		CircleWest.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
		CircleEast.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
		Animation.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
		bb_main.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
	}
}
